use_frameworks!

platform :ios, '9.0'

target 'MathematicsOpration_Example' do
  pod 'MathematicsOpration', :path => '../'

  target 'MathematicsOpration_Tests' do
    inherit! :search_paths

    
  end
end
